In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
scores = pd.read_csv('../data/ACT_Scores_by_State.csv').dropna()
scores

,State,2018 Composite,2018 English,2018 Math,2018 Reading,2018 Science,2022 Composite,2022 English,2022 Math,2022 Reading,2022 Science,RegionDROP,Region
0,Alabama,19.1,18.9,18.3,19.6,19.0,18.0,17.3,17.4,18.5,18.2,South,South
1,Alaska,20.8,19.8,20.6,21.6,20.7,20.4,19.3,20.0,21.4,20.4,West,West
2,Arizona,19.2,18.2,19.4,19.5,19.2,18.4,17.3,18.5,18.8,18.5,West,West
3,Arkansas,19.4,19.1,18.9,19.7,19.4,18.8,18.3,18.1,19.2,19.1,South,South
4,California,22.7,22.5,22.5,23.0,22.1,26.5,26.9,25.6,27.3,25.8,West,West
5,Colorado,23.9,23.9,23.2,24.4,23.5,23.2,23.0,22.4,24.0,23.0,West,West
6,Connecticut,25.6,26.0,24.8,26.1,24.9,26.3,26.8,25.3,27.1,25.7,Northeast,Northeast
7,Delaware,23.8,23.7,23.1,24.5,23.4,24.9,25.3,23.6,26.1,24.3,Northeast,Northeast
8,Florida,19.9,19.2,19.3,21.1,19.5,19.0,18.5,18.4,20.0,18.8,South,South
9,Georgia,21.4,20.9,20.7,22.1,21.2,21.6,21.0,20.8,22.5,21.5,South,South
10,Hawaii,18.9,18.2,19.0,19.1,19.0,18.8,17.6,18.6,19.4,19.1,West,West
11,Idaho,22.3,21.9,21.6,23.2,22.1,22.8,22.3,22.2,23.7,22.6,West,West
12,Illinois,23.9,24.1,23.4,24.2,23.4,24.5,24.8,23.7,25.2,24.0,Midwest,Midwest
13,Indiana,22.5,21.9,22.3,23.1,22.2,22.8,22.1,22.5,23.7,22.5,Midwest,Midwest
14,Iowa,21.8,21.0,21.2,22.5,22.0,21.4,20.4,20.6,22.3,21.6,Midwest,Midwest
15,Kansas,21.6,21.0,21.1,22.3,21.5,19.9,18.9,19.4,20.6,20.1,Midwest,Midwest
16,Kentucky,20.2,19.9,19.7,20.8,20.1,18.6,17.8,18.0,19.2,18.7,South,South
17,Louisiana,19.2,19.0,18.5,19.6,19.1,18.1,17.6,17.4,18.6,18.3,South,South
18,Maine,24.0,23.8,23.6,24.7,23.4,25.1,25.2,23.7,26.2,24.6,Northeast,Northeast
19,Maryland,22.5,22.1,22.0,23.1,22.2,24.4,24.6,23.0,25.4,23.9,Northeast,Northeast
20,Massachusetts,25.5,25.5,25.2,25.9,24.7,26.5,26.6,25.6,27.3,25.8,20Northeast,Northeast
21,Michigan,24.4,24.5,23.9,24.7,23.9,24.6,24.7,23.9,25.2,24.2,21Midwest,Midwest
22,Minnesota,21.3,20.2,21.4,21.7,21.4,21.0,19.7,20.7,21.7,21.4,22Midwest,Midwest
23,Mississippi,18.6,18.2,18.1,18.9,18.6,17.8,17.2,17.4,18.2,18.0,23South,South
24,Missouri,20.0,19.5,19.7,20.5,20.0,20.2,19.5,19.5,21.0,20.4,24Midwest,Midwest
25,Montana,20.0,18.7,19.9,20.7,20.0,19.3,18.0,19.0,20.1,19.5,25West,West
26,Nebraska,20.1,19.4,19.8,20.4,20.1,19.4,18.6,19.1,19.8,19.6,26Midwest,Midwest
27,Nevada,17.7,16.6,17.8,18.0,17.9,17.3,16.1,17.1,17.8,17.6,27West,West
28,New Hampshire,25.1,25.1,24.7,25.6,24.4,25.7,25.7,25.0,26.5,25.2,28Northeast,Northeast
29,New Jersey,23.7,23.8,23.6,24.0,23.0,24.6,24.9,23.9,25.1,24.0,29Northeast,Northeast
30,New Mexico,19.4,18.3,19.1,20.1,19.7,19.8,18.7,19.1,20.9,20.1,30West,West
31,New York,24.5,24.2,24.2,24.9,24.2,25.3,25.2,24.6,26.0,25.0,31Northeast,Northeast
32,North Carolina,19.1,18.0,19.3,19.5,19.2,18.5,17.1,18.5,19.2,18.8,32South,South
33,North Dakota,20.3,19.1,20.3,20.7,20.5,19.2,17.9,19.1,19.7,19.6,33Midwest,Midwest
34,Ohio,20.3,19.3,20.3,20.8,20.4,19.4,18.2,19.2,20.0,19.7,34Midwest,Midwest
35,Oklahoma,19.3,18.4,18.8,20.1,19.4,17.9,17.0,17.3,18.6,18.2,35South,South
36,Oregon,21.3,20.6,20.9,21.9,21.1,23.0,22.5,22.0,24.2,22.8,36West,West
37,Pennsylvania,23.5,23.3,23.2,24.0,23.1,24.4,24.3,23.7,25.2,24.0,37Northeast,Northeast
38,Rhode Island,24.2,24.4,23.6,25.0,23.5,25.2,25.3,24.0,26.2,24.7,38Northeast,Northeast
39,South Carolina,18.3,17.3,18.2,18.6,18.5,18.9,17.8,18.5,19.6,19.1,39South,South
40,South Dakota,21.9,20.8,21.6,22.4,22.2,21.5,20.5,21.2,22.2,21.7,40Midwest,Midwest
41,Tennessee,19.6,19.4,19.1,19.9,19.6,18.6,18.0,18.1,19.0,18.6,41South,South
42,Texas,20.6,19.6,20.6,21.1,20.8,19.8,18.7,19.5,20.4,19.9,42South,South
43,Utah,20.4,19.7,19.9,20.9,20.5,19.9,18.9,19.4,20.6,20.2,43West,West
44,Vermont,24.1,23.9,23.4,24.9,23.8,23.7,23.4,22.4,25.0,23.5,44Northeast,Northeast
45,Virginia,23.9,23.8,23.3,24.7,23.5,24.6,24.6,23.5,25.7,24.3,45South,South
46,Washington,22.2,21.4,22.2,22.7,22.0,24.6,24.3,23.6,25.6,24.3,46West,West
47,West Virginia,20.3,19.8,19.4,21.3,20.4,20.5,20.2,19.4,21.4,20.4,47South,South
48,Wisconsin,20.5,19.8,20.3,20.6,20.8,19.4,18.3,19.3,19.7,19.8,48Midwest,Midwest
49,Wyoming,20.0,19.0,19.7,20.6,20.3,19.2,18.1,18.9,20.0,19.5,49West,West

In [27]:
scores.columns.drop('RegionDROP')

Index(['State', '2018 Composite', '2018 English', '2018 Math', '2018 Reading',
       '2018 Science', '2022 Composite', '2022 English', '2022 Math ',
       '2022 Reading', '2022 Science', 'Region'],
      dtype='object')

In [3]:
scores = scores.drop(['RegionDROP'], axis=1)

In [31]:
scores

,State,2018 Composite,2018 English,2018 Math,2018 Reading,2018 Science,2022 Composite,2022 English,2022 Math,2022 Reading,2022 Science,Region
0,Alabama,19.1,18.9,18.3,19.6,19.0,18.0,17.3,17.4,18.5,18.2,South
1,Alaska,20.8,19.8,20.6,21.6,20.7,20.4,19.3,20.0,21.4,20.4,West
2,Arizona,19.2,18.2,19.4,19.5,19.2,18.4,17.3,18.5,18.8,18.5,West
3,Arkansas,19.4,19.1,18.9,19.7,19.4,18.8,18.3,18.1,19.2,19.1,South
4,California,22.7,22.5,22.5,23.0,22.1,26.5,26.9,25.6,27.3,25.8,West
5,Colorado,23.9,23.9,23.2,24.4,23.5,23.2,23.0,22.4,24.0,23.0,West
6,Connecticut,25.6,26.0,24.8,26.1,24.9,26.3,26.8,25.3,27.1,25.7,Northeast
7,Delaware,23.8,23.7,23.1,24.5,23.4,24.9,25.3,23.6,26.1,24.3,Northeast
8,Florida,19.9,19.2,19.3,21.1,19.5,19.0,18.5,18.4,20.0,18.8,South
9,Georgia,21.4,20.9,20.7,22.1,21.2,21.6,21.0,20.8,22.5,21.5,South
10,Hawaii,18.9,18.2,19.0,19.1,19.0,18.8,17.6,18.6,19.4,19.1,West
11,Idaho,22.3,21.9,21.6,23.2,22.1,22.8,22.3,22.2,23.7,22.6,West
12,Illinois,23.9,24.1,23.4,24.2,23.4,24.5,24.8,23.7,25.2,24.0,Midwest
13,Indiana,22.5,21.9,22.3,23.1,22.2,22.8,22.1,22.5,23.7,22.5,Midwest
14,Iowa,21.8,21.0,21.2,22.5,22.0,21.4,20.4,20.6,22.3,21.6,Midwest
15,Kansas,21.6,21.0,21.1,22.3,21.5,19.9,18.9,19.4,20.6,20.1,Midwest
16,Kentucky,20.2,19.9,19.7,20.8,20.1,18.6,17.8,18.0,19.2,18.7,South
17,Louisiana,19.2,19.0,18.5,19.6,19.1,18.1,17.6,17.4,18.6,18.3,South
18,Maine,24.0,23.8,23.6,24.7,23.4,25.1,25.2,23.7,26.2,24.6,Northeast
19,Maryland,22.5,22.1,22.0,23.1,22.2,24.4,24.6,23.0,25.4,23.9,Northeast
20,Massachusetts,25.5,25.5,25.2,25.9,24.7,26.5,26.6,25.6,27.3,25.8,Northeast
21,Michigan,24.4,24.5,23.9,24.7,23.9,24.6,24.7,23.9,25.2,24.2,Midwest
22,Minnesota,21.3,20.2,21.4,21.7,21.4,21.0,19.7,20.7,21.7,21.4,Midwest
23,Mississippi,18.6,18.2,18.1,18.9,18.6,17.8,17.2,17.4,18.2,18.0,South
24,Missouri,20.0,19.5,19.7,20.5,20.0,20.2,19.5,19.5,21.0,20.4,Midwest
25,Montana,20.0,18.7,19.9,20.7,20.0,19.3,18.0,19.0,20.1,19.5,West
26,Nebraska,20.1,19.4,19.8,20.4,20.1,19.4,18.6,19.1,19.8,19.6,Midwest
27,Nevada,17.7,16.6,17.8,18.0,17.9,17.3,16.1,17.1,17.8,17.6,West
28,New Hampshire,25.1,25.1,24.7,25.6,24.4,25.7,25.7,25.0,26.5,25.2,Northeast
29,New Jersey,23.7,23.8,23.6,24.0,23.0,24.6,24.9,23.9,25.1,24.0,Northeast
30,New Mexico,19.4,18.3,19.1,20.1,19.7,19.8,18.7,19.1,20.9,20.1,West
31,New York,24.5,24.2,24.2,24.9,24.2,25.3,25.2,24.6,26.0,25.0,Northeast
32,North Carolina,19.1,18.0,19.3,19.5,19.2,18.5,17.1,18.5,19.2,18.8,South
33,North Dakota,20.3,19.1,20.3,20.7,20.5,19.2,17.9,19.1,19.7,19.6,Midwest
34,Ohio,20.3,19.3,20.3,20.8,20.4,19.4,18.2,19.2,20.0,19.7,Midwest
35,Oklahoma,19.3,18.4,18.8,20.1,19.4,17.9,17.0,17.3,18.6,18.2,South
36,Oregon,21.3,20.6,20.9,21.9,21.1,23.0,22.5,22.0,24.2,22.8,West
37,Pennsylvania,23.5,23.3,23.2,24.0,23.1,24.4,24.3,23.7,25.2,24.0,Northeast
38,Rhode Island,24.2,24.4,23.6,25.0,23.5,25.2,25.3,24.0,26.2,24.7,Northeast
39,South Carolina,18.3,17.3,18.2,18.6,18.5,18.9,17.8,18.5,19.6,19.1,South
40,South Dakota,21.9,20.8,21.6,22.4,22.2,21.5,20.5,21.2,22.2,21.7,Midwest
41,Tennessee,19.6,19.4,19.1,19.9,19.6,18.6,18.0,18.1,19.0,18.6,South
42,Texas,20.6,19.6,20.6,21.1,20.8,19.8,18.7,19.5,20.4,19.9,South
43,Utah,20.4,19.7,19.9,20.9,20.5,19.9,18.9,19.4,20.6,20.2,West
44,Vermont,24.1,23.9,23.4,24.9,23.8,23.7,23.4,22.4,25.0,23.5,Northeast
45,Virginia,23.9,23.8,23.3,24.7,23.5,24.6,24.6,23.5,25.7,24.3,South
46,Washington,22.2,21.4,22.2,22.7,22.0,24.6,24.3,23.6,25.6,24.3,West
47,West Virginia,20.3,19.8,19.4,21.3,20.4,20.5,20.2,19.4,21.4,20.4,South
48,Wisconsin,20.5,19.8,20.3,20.6,20.8,19.4,18.3,19.3,19.7,19.8,Midwest
49,Wyoming,20.0,19.0,19.7,20.6,20.3,19.2,18.1,18.9,20.0,19.5,West

Region     State            2018 Composite  2018 English  2018 Math  2018 Reading  2018 Science  2022 Composite  2022 English  2022 Math   2022 Reading  2022 Science
Midwest    Illinois         23.9            24.1          23.4       24.2          23.4          24.5            24.8          23.7        25.2          24.0            1
           Indiana          22.5            21.9          22.3       23.1          22.2          22.8            22.1          22.5        23.7          22.5            1
           Iowa             21.8            21.0          21.2       22.5          22.0          21.4            20.4          20.6        22.3          21.6            1
           Kansas           21.6            21.0          21.1       22.3          21.5          19.9            18.9          19.4        20.6          20.1            1
           Michigan         24.4            24.5          23.9       24.7          23.9          24.6            24.7          23.9        25.2          24.2            1
           Minnesota        21.3            20.2          21.4       21.7          21.4          21.0            19.7          20.7        21.7          21.4            1
           Missouri         20.0            19.5          19.7       20.5          20.0          20.2            19.5          19.5        21.0          20.4            1
           Nebraska         20.1            19.4          19.8       20.4          20.1          19.4            18.6          19.1        19.8          19.6            1
           North Dakota     20.3            19.1          20.3       20.7          20.5          19.2            17.9          19.1        19.7          19.6            1
           Ohio             20.3            19.3          20.3       20.8          20.4          19.4            18.2          19.2        20.0          19.7            1
           South Dakota     21.9            20.8          21.6       22.4          22.2          21.5            20.5          21.2        22.2          21.7            1
           Wisconsin        20.5            19.8          20.3       20.6          20.8          19.4            18.3          19.3        19.7          19.8            1
Northeast  Connecticut      25.6            26.0          24.8       26.1          24.9          26.3            26.8          25.3        27.1          25.7            1
           Delaware         23.8            23.7          23.1       24.5          23.4          24.9            25.3          23.6        26.1          24.3            1
           Maine            24.0            23.8          23.6       24.7          23.4          25.1            25.2          23.7        26.2          24.6            1
           Maryland         22.5            22.1          22.0       23.1          22.2          24.4            24.6          23.0        25.4          23.9            1
           Massachusetts    25.5            25.5          25.2       25.9          24.7          26.5            26.6          25.6        27.3          25.8            1
           New Hampshire    25.1            25.1          24.7       25.6          24.4          25.7            25.7          25.0        26.5          25.2            1
           New Jersey       23.7            23.8          23.6       24.0          23.0          24.6            24.9          23.9        25.1          24.0            1
           New York         24.5            24.2          24.2       24.9          24.2          25.3            25.2          24.6        26.0          25.0            1
           Pennsylvania     23.5            23.3          23.2       24.0          23.1          24.4            24.3          23.7        25.2          24.0            1
           Rhode Island     24.2            24.4          23.6       25.0          23.5          25.2            25.3          24.0        26.2          24.7            1
           Vermont          24.1            23.9          23.4       24.9          23.8          23.7            23.4          22.4        25.0          23.5            1
South      Kentucky         20.2            19.9          19.7       20.8          20.1          18.6            17.8          18.0        19.2          18.7            1
           Louisiana        19.2            19.0          18.5       19.6          19.1          18.1            17.6          17.4        18.6          18.3            1
           Mississippi      18.6            18.2          18.1       18.9          18.6          17.8            17.2          17.4        18.2          18.0            1
           North Carolina   19.1            18.0          19.3       19.5          19.2          18.5            17.1          18.5        19.2          18.8            1
           Oklahoma         19.3            18.4          18.8       20.1          19.4          17.9            17.0          17.3        18.6          18.2            1
           South Carolina   18.3            17.3          18.2       18.6          18.5          18.9            17.8          18.5        19.6          19.1            1
           Tennessee        19.6            19.4          19.1       19.9          19.6          18.6            18.0          18.1        19.0          18.6            1
           Texas            20.6            19.6          20.6       21.1          20.8          19.8            18.7          19.5        20.4          19.9            1
           Virginia         23.9            23.8          23.3       24.7          23.5          24.6            24.6          23.5        25.7          24.3            1
           West Virginia    20.3            19.8          19.4       21.3          20.4          20.5            20.2          19.4        21.4          20.4            1
           Georgia          21.4            20.9          20.7       22.1          21.2          21.6            21.0          20.8        22.5          21.5            1
           Florida          19.9            19.2          19.3       21.1          19.5          19.0            18.5          18.4        20.0          18.8            1
           Arkansas         19.4            19.1          18.9       19.7          19.4          18.8            18.3          18.1        19.2          19.1            1
           Alabama          19.1            18.9          18.3       19.6          19.0          18.0            17.3          17.4        18.5          18.2            1
West       Alaska           20.8            19.8          20.6       21.6          20.7          20.4            19.3          20.0        21.4          20.4            1
           Arizona          19.2            18.2          19.4       19.5          19.2          18.4            17.3          18.5        18.8          18.5            1
           California       22.7            22.5          22.5       23.0          22.1          26.5            26.9          25.6        27.3          25.8            1
           Colorado         23.9            23.9          23.2       24.4          23.5          23.2            23.0          22.4        24.0          23.0            1
           Hawaii           18.9            18.2          19.0       19.1          19.0          18.8            17.6          18.6        19.4          19.1            1
           Idaho            22.3            21.9          21.6       23.2          22.1          22.8            22.3          22.2        23.7          22.6            1
           Montana          20.0            18.7          19.9       20.7          20.0          19.3            18.0          19.0        20.1          19.5            1
           Nevada           17.7            16.6          17.8       18.0          17.9          17.3            16.1          17.1        17.8          17.6            1
           New Mexico       19.4            18.3          19.1       20.1          19.7          19.8            18.7          19.1        20.9          20.1            1
           Oregon           21.3            20.6          20.9       21.9          21.1          23.0            22.5          22.0        24.2          22.8            1
           Utah             20.4            19.7          19.9       20.9          20.5          19.9            18.9          19.4        20.6          20.2            1
           Washington       22.2            21.4          22.2       22.7          22.0          24.6            24.3          23.6        25.6          24.3            1
           Wyoming          20.0            19.0          19.7       20.6          20.3          19.2            18.1          18.9        20.0          19.5            1
Name: count, dtype: int64

In [46]:
scores['State'] = scores['State'].astype('string')

In [47]:
scores['Region'] = scores['Region'].astype('string')

In [48]:
scores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   State           50 non-null     string
 1   2018 Composite  50 non-null     float64
 2   2018 English    50 non-null     float64
 3   2018 Math       50 non-null     float64
 4   2018 Reading    50 non-null     float64
 5   2018 Science    50 non-null     float64
 6   2022 Composite  50 non-null     float64
 7   2022 English    50 non-null     float64
 8   2022 Math       50 non-null     float64
 9   2022 Reading    50 non-null     float64
 10  2022 Science    50 non-null     float64
 11  Region          50 non-null     string
dtypes: float64(10), string(2)
memory usage: 4.8 KB

In [103]:
state_regions = scores[['Region', 'State']]
state_regions

       Region            State
0       South         Alabama
1        West          Alaska
2        West         Arizona
3       South        Arkansas
4        West      California
5        West        Colorado
6   Northeast     Connecticut
7   Northeast        Delaware
8       South         Florida
9       South         Georgia
10       West          Hawaii
11       West           Idaho
12    Midwest        Illinois
13    Midwest         Indiana
14    Midwest            Iowa
15    Midwest          Kansas
16      South        Kentucky
17      South       Louisiana
18  Northeast           Maine
19  Northeast        Maryland
20  Northeast   Massachusetts
21    Midwest        Michigan
22    Midwest       Minnesota
23      South     Mississippi
24    Midwest        Missouri
25       West         Montana
26    Midwest        Nebraska
27       West          Nevada
28  Northeast   New Hampshire
29  Northeast      New Jersey
30       West      New Mexico
31  Northeast        New York
32      South  North Carolina
33    Midwest    North Dakota
34    Midwest            Ohio
35      South        Oklahoma
36       West          Oregon
37  Northeast    Pennsylvania
38  Northeast    Rhode Island
39      South  South Carolina
40    Midwest    South Dakota
41      South       Tennessee
42      South           Texas
43       West            Utah
44  Northeast         Vermont
45      South        Virginia
46       West      Washington
47      South   West Virginia
48    Midwest       Wisconsin
49       West         Wyoming

In [86]:
state_regions = state_regions.groupby('Region').count()

In [87]:
state_regions = state_regions.reset_index()
state_regions

      Region  State
0    Midwest     12
1  Northeast     11
2      South     14
3       West     13

In [94]:
state_regions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Region  4 non-null      string
 1   State   4 non-null      int64
dtypes: int64(1), string(1)
memory usage: 196.0 bytes

In [4]:
score_by_region = scores[['Region', '2018 Composite']]

In [5]:
score_by_region.groupby('Region').mean().reset_index()

      Region  2018 Composite
0    Midwest       21.550000
1  Northeast       24.227273
2      South       19.921429
3       West       20.676923